_target_: pydantic_ai.models.openai.OpenAIChatModel
_recursive_: true
model_name: local
provider:
  _target_: pydantic_ai.providers.openai.OpenAIProvider
  base_url: http://localhost:9191/v1
  api_key: "null"

